"""add cover field to video

Revision ID: 8e7e7d1038cf
Revises: 5d1541c70b57
Create Date: 2025-07-17 15:09:03.903685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7e7d1038cf'
down_revision = '5d1541c70b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
