"""change video id to uuid string

Revision ID: 970b699590b6
Revises: 8e7e7d1038cf
Create Date: 2025-07-17 15:32:18.002501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970b699590b6'
down_revision = '8e7e7d1038cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
